apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: rails-deployment 
  labels: 
    app: rails-backend 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: rails-backend 
  template: 
    metadata: 
      labels: 
        app: rails-backend 
    spec: 
      containers:
      - name: rubysocial 
        image: us-docker.pkg.dev/even-ally-356808/gcr.io/rubychat:latest
        #image: gcr.io/even-ally-356808/rubychat
        ports: 
        - containerPort: 3000 
        env:
          - name: RAILS_ENV 
            value: production 
          - name: RAILS_MASTER_KEY 
            valueFrom: 
              secretKeyRef: 
                name: rails-master-key 
                key: rails-master-key 
          - name: DATABASE_HOST 
            value: 34.132.228.8
          - name: DATABASE_USERNAME 
            value: postgres 
          - name: DATABASE_PASSWORD 
            valueFrom: 
              secretKeyRef: 
                name: database-password 
                key: database-password
      imagePullSecrets:
        - name: image-key
      
        