apiVersion: v1 
kind: Service 
metadata: 
  name: rails-backend 
spec: 
  type: LoadBalancer 
  selector: 
    app: rails-backend 
  ports: 
    - protocol: TCP 
      port: 80 
      targetPort: 3000 