#Deploy with helm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
 on: 
   workflow_dispatch: 
     inputs: 
       version: 
         description: 'Version to release (ex. v0.1)' 
         required: true 
  
 jobs: 
   deploy: 
     name: Deploy rubysocial to production cluster 
     runs-on: ubuntu-latest 
     steps: 
       - name: Check Out Repo 
         uses: actions/checkout@v2 
  
       - name: Login to Google Cloud
         id: auth 
         uses: google-github-actions/auth@v0 
         with: 
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
       # Setup gcloud CLI
       #- uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
       #  with:
       #    version: '270.0.0'
       #    service_account_email: ${{ secrets.GKE_EMAIL }}
       #    service_account_key: ${{ secrets.GKE_KEY }} 
  
       - name: Configure docker to use the gcloud command-line tool as a credential helper
         run: |
            gcloud auth configure-docker
       # Install helm
       - name: Install Helm
         run: |
           curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash 
  
       - name: Install kube config 
         env: 
           INPUT_KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }} 
         run: | 
           mkdir ~/.kube/ || true 
           if [ -f "~/.kube/config" ]; then 
             echo -e "\033[36mExisting kubeconfig found, using that and ignoring input\033[0m" 
           else 
             echo -e "\033[36mUsing kubeconfig from input\033[0m" 
             echo "${INPUT_KUBECONFIG}" > ~/.kube/config 
           fi 
           chmod 700 ~/.kube/config 
       - run: wc -l 
  
       - name: Deploy to Kubernetes 
         run: 
           helm upgrade rubysocial ~/git/rubysocial/deployment/kubernetes/helm/rubychat/ --install --wait --atomic  --set=version=${{ github.event.inputs.version }} --kubeconfig ~/.kube/config 