on: 
   push: 
     tags: 
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 
jobs: 
   backend-frontend:
    name: Create backend and frontend releases 
    runs-on: ubuntu-latest
    env:
       IMAGE_NAME: RUBYCHAT
       PROJECT_ID: even-ally-356808 
    steps: 
       - name: Check Out Repo 
         uses: actions/checkout@v2 
  
       - name: Get the version 
         id: get_version 
         run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3) 
  
       - name: Login to Google Cloud
         id: auth 
         uses: google-github-actions/auth@v0.3.1 
         with: 
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }} 
  
       - name: Automatic Tagging of Releases
         id: increment-git-tag
         run: |
          bash ./scripts/git_update.sh -v major

       - name: Configure Docker Client
         run: |-
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker us-west2-docker.pkg.dev --quiet

       - name: Build and push 
         id: docker_build 
         uses: docker/build-push-action@v2 
         with: 
           context: ./ 
           file: ./Dockerfile 
           build-args: | 
             RAILS_KEY=${{ secrets.RAILS_KEY }} 
       - name: Image digest 
         run: echo ${{ steps.docker_build.outputs.digest }}

       - name: Push Docker Image to Container Registry (GCR)
         env:
         GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
         run: |-
           docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
           docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
           docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
           docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

       - name: Push Docker Image to Artifact Registry
         env:
         GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
         run: |-
           docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
           docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
           docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
           docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG 